export const WORDS = [
  'Iveto Sangalo',
  'Mato Atlântico',
  'Casos Bahio',
  'Rito Cadilaco',
  'Madonno',
  'Patricio Poeto',
  'Samsungo',
  'Tubaíno',
  'Valesco Popozudo',
  'Braganço Paulisto',
  'Caldo de Cano',
  'Chora na Tora',
  'Salado de Fruto',
  'Emicido',
  'Sapopembo',
  'Diademo',
  'Biblioteco',
  'Caso Lotérico',
  'Arábio Saudito',
  'Ludmillo',
  'Silos Malafaio',
  'Caganeiro',
  'Cracolândio',
  'Cnpjoto',
  'Aeromoço',
  'Lady Gago',
  'Copocabano',
  'Ipanemo',
  'Olivio Palito',
  'Seu Madrugo',
  'Anchieto',
  'Netflixo',
  'Tim Maio',
  'Frigideiro',
  'Uberlândio',
  'Capivaro',
  'Fátimo Bernardo',
  'Magazino Luizo',
  'Inseticido',
  'Mosquito',
  'Delicio',
  'Mama Penca',
  'Boca Aberta',
  'Vidoca',
  'iPhono',
  'Lamparino',
  'Cadelo',
  'Boneco Ventríloquo',
  'Prostituto',
  'Dipirono',
  'Tilápio',
  'Prexeco',
  'Siririco',
  'Calabreso',
  'Danono',
  'Meia Calça',
  'Tartarugo',
  'Chupeto'
]
